parameters:
#    hg_file_repository.example.class: HG\FileRepositoryBundle\Example

services:
#    hg_file_repository.example:
#        class: %hg_file_repository.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    hg_file_repository.filemanager:
        class: %hg_file_repository.manager_class%
        arguments: [@doctrine.orm.entity_manager, "@hg_file_repository.upload_manager", %hg_file_repository.types%, @kernel, @security.context]
        calls:
            - [setBaseDir, [%hg_file_repository.base_dir%]]
            - [setSecureDirname, [%hg_file_repository.secure_dir%]]
            - [setSecureRole, [%hg_file_repository.secure_role%]]

    hg_file_repository.twig.file_repository_extension:
        class: HG\FileRepositoryBundle\Twig\HGFileRepositoryExtension
        arguments: [@hg_file_repository.filemanager, @router]
        tags:
            - { name: twig.extension }

    hg_file_repository.type.file_repository:
        class: HG\FileRepositoryBundle\Form\Type\FileRepositoryType
        arguments: ["@hg_file_repository.filemanager", "@hg_file_repository.upload_manager", %hg_file_repository.upload_request_type%]
        tags:
            - { name: form.type, alias: file_repository }

    hg_file_repository.subscriber:
        class: HG\FileRepositoryBundle\EventListener\FileRepositoryUploadSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hg_file_repository.upload_manager:
        class: %hg_file_repository.upload_manager_class%

    hg_file_repository.type.file_repository_uploadify:
        class: HG\FileRepositoryBundle\Form\Type\FileRepositoryUploadifyType
        arguments: ["@hg_file_repository.filemanager"]
        calls:
            - [setParamName, ['%hg_utils.session_param_name%']]
            - [setRouter, ['@router']]
        tags:
            - { name: form.type, alias: file_uploadify }
