<?php

namespace HG\FileRepositoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HGFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HGFileRepository extends EntityRepository
{
  public function getMaxId()
  {
    return $this->createQueryBuilder('f')
    ->select('MAX(f.fil_id)')
    ->getQuery()
    ->getSingleScalarResult();
  }
}
